package nurse.little.com.mylittlenurse;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import nurse.little.com.mylittlenurse.SickPeople;
import nurse.little.com.mylittlenurse.DiaylsDate;
import nurse.little.com.mylittlenurse.XuanJiao;

import nurse.little.com.mylittlenurse.SickPeopleDao;
import nurse.little.com.mylittlenurse.DiaylsDateDao;
import nurse.little.com.mylittlenurse.XuanJiaoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig sickPeopleDaoConfig;
    private final DaoConfig diaylsDateDaoConfig;
    private final DaoConfig xuanJiaoDaoConfig;

    private final SickPeopleDao sickPeopleDao;
    private final DiaylsDateDao diaylsDateDao;
    private final XuanJiaoDao xuanJiaoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        sickPeopleDaoConfig = daoConfigMap.get(SickPeopleDao.class).clone();
        sickPeopleDaoConfig.initIdentityScope(type);

        diaylsDateDaoConfig = daoConfigMap.get(DiaylsDateDao.class).clone();
        diaylsDateDaoConfig.initIdentityScope(type);

        xuanJiaoDaoConfig = daoConfigMap.get(XuanJiaoDao.class).clone();
        xuanJiaoDaoConfig.initIdentityScope(type);

        sickPeopleDao = new SickPeopleDao(sickPeopleDaoConfig, this);
        diaylsDateDao = new DiaylsDateDao(diaylsDateDaoConfig, this);
        xuanJiaoDao = new XuanJiaoDao(xuanJiaoDaoConfig, this);

        registerDao(SickPeople.class, sickPeopleDao);
        registerDao(DiaylsDate.class, diaylsDateDao);
        registerDao(XuanJiao.class, xuanJiaoDao);
    }
    
    public void clear() {
        sickPeopleDaoConfig.getIdentityScope().clear();
        diaylsDateDaoConfig.getIdentityScope().clear();
        xuanJiaoDaoConfig.getIdentityScope().clear();
    }

    public SickPeopleDao getSickPeopleDao() {
        return sickPeopleDao;
    }

    public DiaylsDateDao getDiaylsDateDao() {
        return diaylsDateDao;
    }

    public XuanJiaoDao getXuanJiaoDao() {
        return xuanJiaoDao;
    }

}
