package nurse.little.com.mylittlenurse;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table "DIAYLS_DATE".
 */
public class DiaylsDate implements Serializable {

    private Long id;
    private String date;
    private String name;

    public DiaylsDate() {
    }

    public DiaylsDate(Long id) {
        this.id = id;
    }

    public DiaylsDate(Long id, String date, String name) {
        this.id = id;
        this.date = date;
        this.name = name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
