package nurse.little.com.mylittlenurse;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table "SICK_HISTORY".
 */
public class SickHistory implements Serializable{

    private Long id;
    private String time;
    private String name;
    private String sickDes;

    public SickHistory() {
    }

    public SickHistory(Long id) {
        this.id = id;
    }

    public SickHistory(Long id, String time, String name, String sickDes) {
        this.id = id;
        this.time = time;
        this.name = name;
        this.sickDes = sickDes;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSickDes() {
        return sickDes;
    }

    public void setSickDes(String sickDes) {
        this.sickDes = sickDes;
    }

}
