package nurse.little.com.mylittlenurse;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table "SICK_PEOPLE".
 */
public class SickPeople implements Serializable{

    private Long id;
    /** Not-null value. */
    private String name;
    private String age;
    private String sex;
    private String height;
    private String weight;
    private String tel;
    private String time;
    private String mailou;
    private String huayan;
    private String yingyang;
    private String bingshi;

    public SickPeople() {
    }

    public SickPeople(Long id) {
        this.id = id;
    }

    public SickPeople(Long id, String name, String age, String sex, String height, String weight, String tel, String time, String mailou, String huayan, String yingyang, String bingshi) {
        this.id = id;
        this.name = name;
        this.age = age;
        this.sex = sex;
        this.height = height;
        this.weight = weight;
        this.tel = tel;
        this.time = time;
        this.mailou = mailou;
        this.huayan = huayan;
        this.yingyang = yingyang;
        this.bingshi = bingshi;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public String getAge() {
        return age;
    }

    public void setAge(String age) {
        this.age = age;
    }

    public String getSex() {
        return sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    public String getHeight() {
        return height;
    }

    public void setHeight(String height) {
        this.height = height;
    }

    public String getWeight() {
        return weight;
    }

    public void setWeight(String weight) {
        this.weight = weight;
    }

    public String getTel() {
        return tel;
    }

    public void setTel(String tel) {
        this.tel = tel;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public String getMailou() {
        return mailou;
    }

    public void setMailou(String mailou) {
        this.mailou = mailou;
    }

    public String getHuayan() {
        return huayan;
    }

    public void setHuayan(String huayan) {
        this.huayan = huayan;
    }

    public String getYingyang() {
        return yingyang;
    }

    public void setYingyang(String yingyang) {
        this.yingyang = yingyang;
    }

    public String getBingshi() {
        return bingshi;
    }

    public void setBingshi(String bingshi) {
        this.bingshi = bingshi;
    }

}
