package nurse.little.com.mylittlenurse;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import cn.bmob.v3.BmobObject;

/**
 * Entity mapped to table "XUAN_JIAO".
 */
public class XuanJiao extends BmobObject {

    private Long id;
    private String time;
    private String content;

    public XuanJiao() {
    }

    public XuanJiao(Long id) {
        this.id = id;
    }

    public XuanJiao(Long id, String time, String content) {
        this.id = id;
        this.time = time;
        this.content = content;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

}
